default: &DEFAULT
  adapter: postgresql

development:
  <<: *DEFAULT
  database: knotebooks_development

test: &TEST
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

cucumber:
  <<: *TEST

production:
  <<: *DEFAULT
  database: knotebooks_production
